# Generated by Django 3.1.1 on 2020-09-23 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldetail',
            name='created_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='personaldetail',
            name='date_of_birth',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
