# Generated by Django 3.1.1 on 2020-10-02 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200923_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldetail',
            name='account_number',
            field=models.BigIntegerField(null=True, unique=True),
        ),
    ]
