# Generated by Django 3.1.1 on 2020-10-27 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_personaldetail_account_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldetail',
            name='account_password',
            field=models.TextField(max_length=8, null=True, unique=True),
        ),
    ]
